// <auto-generated />
using System;
using EmployeeManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20181104101048_blabla")]
    partial class blabla
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("SecondName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new { Id = new Guid("11111111-1111-1111-1111-111111111111"), DateOfBirth = new DateTime(1945, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), FirstName = "Hans", SecondName = "Wurst" },
                        new { Id = new Guid("22222222-2222-2222-2222-222222222222"), DateOfBirth = new DateTime(1933, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), FirstName = "Jim", SecondName = "Beam" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
